name: Docker Compose Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hoverkraft-tech/compose-action@v1.5.1
    - name: Build the Docker image
      run: docker-compose build